wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1654970343
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: InceptionV3
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 5
dataset:
  desc: null
  value: Flower recognition
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.005
